export const FETCH_STARTED = 'DRAFTTABLE/FETCH_STARTED';
export const FETCH_SUCCESS = 'DRAFTTABLE/FETCH_SUCCESS';
export const FETCH_FAILURE = 'DRAFTTABLE/FETCH_FAILURE';
export const DELETE_STARTED = 'DRAFTTABLE/DELETE_STARTED';
export const DELETE_SUCCESS = 'DRAFTTABLE/DELETE_SUCCESS';
export const DELETE_FAILURE = 'DRAFTTABLE/DELETE_FAILURE';
export const SET_FILTER = 'DRAFTTABLE/SET_FILTER';