export const FILTER_CHANGE = 'MY_DRAFT/FILTER_CHANGE';

export const FETCH_STARTED = 'MY_DRAFT/FETCH_STARTED';
export const FETCH_SUCCESS = 'MY_DRAFT/FETCH_SUCCESS';
export const FETCH_FAILURE = 'MY_DRAFT/FETCH_FAILURE';